[package]
name = "my-project"
version = "0.1.0"
authors = ["bob", "alice"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
pulldown-cmark = "0.9.1"
grass = "0.11.0"
